name: Daily Data Collection

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-datacollection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run datacollection
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python datacollection.py


